## YAML Template.
---
driverDB: com.mysql.jdbc.Driver
##urlDB: jdbc:mysql://localhost:3306/baselocal?useSSL=false
##userDB: root
##passDB: admin
urlDB: jdbc:mysql://sql11.freemysqlhosting.net:3306/sql11212627?useSSL=false
userDB: sql11212627
passDB: LWzV3WksI1
mailFrom: alumno1@iesquevedo.es
smtpServer: smtp.gmail.com
smtpPort: 587
mailPass: alumnodam2
longitudCodigo: 50